In [2]:
import torch


In [7]:
#task1
tensor_A = torch.rand(7, 7)
print("Tensor A (7x7):\n", tensor_A)
tensor_B = torch.rand(1, 7)
print("\nTensor B (1x7):\n", tensor_B)

matmul_result = torch.matmul(tensor_A, tensor_B.T)
print("\nMatrix Multiplication Result (7x1):\n", matmul_result)
print("Result Shape:", matmul_result.shape)

torch.manual_seed(0)
tensor_C = torch.rand(7, 7)
tensor_D = torch.rand(1, 7)


matmul_seeded = torch.matmul(tensor_C, tensor_D.T)
print("\nMatrix Multiplication with Seed (7x1):\n", matmul_seeded)
print("Result Shape:", matmul_seeded.shape)

if torch.cuda.is_available():
    tensor_gpu = tensor_C.to("cuda")
    print("\nTensor moved to GPU ✅")
else:
    print("\nCUDA (GPU) not available on this device ")

Tensor A (7x7):
 tensor([[0.5932, 0.1123, 0.1535, 0.2417, 0.7262, 0.7011, 0.2038],
        [0.6511, 0.7745, 0.4369, 0.5191, 0.6159, 0.8102, 0.9801],
        [0.1147, 0.3168, 0.6965, 0.9143, 0.9351, 0.9412, 0.5995],
        [0.0652, 0.5460, 0.1872, 0.0340, 0.9442, 0.8802, 0.0012],
        [0.5936, 0.4158, 0.4177, 0.2711, 0.6923, 0.2038, 0.6833],
        [0.7529, 0.8579, 0.6870, 0.0051, 0.1757, 0.7497, 0.6047],
        [0.1100, 0.2121, 0.9704, 0.8369, 0.2820, 0.3742, 0.0237]])

Tensor B (1x7):
 tensor([[0.4910, 0.1235, 0.1143, 0.4725, 0.5751, 0.2952, 0.7967]])

Matrix Multiplication Result (7x1):
 tensor([[1.2239],
        [2.0847],
        [1.9002],
        [0.9408],
        [1.5213],
        [1.3606],
        [0.8780]])
Result Shape: torch.Size([7, 1])

Matrix Multiplication with Seed (7x1):
 tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])
Result Shape: torch.Size([7, 1])

CUDA (GPU) not available on this de

In [8]:
# task2
tensor_B = torch.tensor([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(tensor_B)
print("Shape:", tensor_B.shape)
print("Dimensions:", tensor_B.ndim)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Shape: torch.Size([3, 3])
Dimensions: 2


In [9]:
# task3
random_tensor = torch.rand(3, 3)

print(random_tensor)
print("Shape:", random_tensor.shape)
print("Dimensions:", random_tensor.ndim)

tensor([[0.5932, 0.1123, 0.1535],
        [0.2417, 0.7262, 0.7011],
        [0.2038, 0.6511, 0.7745]])
Shape: torch.Size([3, 3])
Dimensions: 2


In [10]:
#task4
torch.manual_seed(0)

A = torch.rand(7, 7)
B = torch.rand(7, 7)

tensor_C = torch.mm(A, B)

print("Matrix A:\n", A)
print("\nMatrix B:\n", B)
print("\nResult (A x B):\n", tensor_C)
print("\nShape of Result:", tensor_C.shape)

Matrix A:
 tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])

Matrix B:
 tensor([[0.4820, 0.8198, 0.9971, 0.6984, 0.5675, 0.8352, 0.2056],
        [0.5932, 0.1123, 0.1535, 0.2417, 0.7262, 0.7011, 0.2038],
        [0.6511, 0.7745, 0.4369, 0.5191, 0.6159, 0.8102, 0.9801],
        [0.1147, 0.3168, 0.6965, 0.9143, 0.9351, 0.9412, 0.5995],
        [0.0652, 0.5460, 0.1872, 0.0340, 0.9442, 0.8802, 0.0012],
        [0.5936, 0.4158, 0.4177, 0.2711, 0.6923, 0.2038, 0.6833],
        [0.7529, 0.8579, 0.6870, 0.0051, 0.1757, 0.7497, 0.6047]])

Result (A x B):
 tensor([[1.5330, 1.4554, 1.4024, 

In [11]:
# task5
first_two_rows = tensor_C[:2]

print("First two rows of tensor_C:\n", first_two_rows)
print("Shape:", first_two_rows.shape)


First two rows of tensor_C:
 tensor([[1.5330, 1.4554, 1.4024, 0.8838, 1.8328, 1.9163, 1.1545],
        [1.3206, 1.7598, 1.6835, 1.4040, 1.9798, 2.3936, 1.2239]])
Shape: torch.Size([2, 7])


In [12]:
# task6
last_three_cols = tensor_C[:, -3:]

print("Last three columns of tensor_C:\n", last_three_cols)
print("Shape:", last_three_cols.shape)


Last three columns of tensor_C:
 tensor([[1.8328, 1.9163, 1.1545],
        [1.9798, 2.3936, 1.2239],
        [2.1883, 2.6374, 1.9347],
        [2.9263, 2.8538, 2.0508],
        [1.8151, 1.8637, 1.2477],
        [2.5260, 2.5496, 1.9016],
        [2.0358, 1.9399, 1.1193]])
Shape: torch.Size([7, 3])


In [13]:
#task7
first_column = tensor_C[:, 0]

print("First column of tensor_C:\n", first_column)
print("Shape:", first_column.shape)


First column of tensor_C:
 tensor([1.5330, 1.3206, 1.6864, 1.9227, 0.9014, 1.3713, 1.1530])
Shape: torch.Size([7])


In [14]:
#task8
reshaped_tensor = tensor_C.reshape(1, 49)

print("Reshaped tensor:\n", reshaped_tensor)
print("New shape:", reshaped_tensor.shape)


Reshaped tensor:
 tensor([[1.5330, 1.4554, 1.4024, 0.8838, 1.8328, 1.9163, 1.1545, 1.3206, 1.7598,
         1.6835, 1.4040, 1.9798, 2.3936, 1.2239, 1.6864, 1.8830, 1.8509, 1.5097,
         2.1883, 2.6374, 1.9347, 1.9227, 2.3338, 2.1738, 1.8497, 2.9263, 2.8538,
         2.0508, 0.9014, 1.0628, 1.2736, 1.3100, 1.8151, 1.8637, 1.2477, 1.3713,
         1.8317, 1.4996, 1.3854, 2.5260, 2.5496, 1.9016, 1.1530, 1.6809, 1.4924,
         0.9540, 2.0358, 1.9399, 1.1193]])
New shape: torch.Size([1, 49])


In [15]:
#task9
concatenated = torch.cat((tensor_C, tensor_C), dim=1)

print("Concatenated tensor:\n", concatenated)
print("New shape:", concatenated.shape)


Concatenated tensor:
 tensor([[1.5330, 1.4554, 1.4024, 0.8838, 1.8328, 1.9163, 1.1545, 1.5330, 1.4554,
         1.4024, 0.8838, 1.8328, 1.9163, 1.1545],
        [1.3206, 1.7598, 1.6835, 1.4040, 1.9798, 2.3936, 1.2239, 1.3206, 1.7598,
         1.6835, 1.4040, 1.9798, 2.3936, 1.2239],
        [1.6864, 1.8830, 1.8509, 1.5097, 2.1883, 2.6374, 1.9347, 1.6864, 1.8830,
         1.8509, 1.5097, 2.1883, 2.6374, 1.9347],
        [1.9227, 2.3338, 2.1738, 1.8497, 2.9263, 2.8538, 2.0508, 1.9227, 2.3338,
         2.1738, 1.8497, 2.9263, 2.8538, 2.0508],
        [0.9014, 1.0628, 1.2736, 1.3100, 1.8151, 1.8637, 1.2477, 0.9014, 1.0628,
         1.2736, 1.3100, 1.8151, 1.8637, 1.2477],
        [1.3713, 1.8317, 1.4996, 1.3854, 2.5260, 2.5496, 1.9016, 1.3713, 1.8317,
         1.4996, 1.3854, 2.5260, 2.5496, 1.9016],
        [1.1530, 1.6809, 1.4924, 0.9540, 2.0358, 1.9399, 1.1193, 1.1530, 1.6809,
         1.4924, 0.9540, 2.0358, 1.9399, 1.1193]])
New shape: torch.Size([7, 14])


In [16]:
# task10
max_value = torch.max(tensor_C)
min_value = torch.min(tensor_C)

print("Maximum value in tensor_C:", max_value.item())
print("Minimum value in tensor_C:", min_value.item())


Maximum value in tensor_C: 2.926337242126465
Minimum value in tensor_C: 0.8838186264038086
